SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `language`;
DROP TABLE IF EXISTS `user_role`;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `role_permission`;
DROP TABLE IF EXISTS `permission`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `item_tag`;
DROP TABLE IF EXISTS `collection_content`;
DROP TABLE IF EXISTS `content`;
DROP TABLE IF EXISTS `collection`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `password_resets`;

SET FOREIGN_KEY_CHECKS = 1;
