package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/ramen-collective/go-cloudbuild-template/internal/graph/generated"
)

// Test is the resolver for the test field.
func (r *mutationResolver) Test(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Test - test"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
